- Fixed message in Linux interface script. - Fixed daemon mode cleanup bug in AgentBootstrap. - Added path overrides in daemon mode. - Moved java option -server or -client to the front, required by JDK. - Moved logger setup from CmdAgent to AgentBootstrap. - Added APIs to obtain master's ip address and the best interface address to communicate against a host. - Starting the agents using master ip address rather than host name. Cuts off name resolution and works better with VPN systems.

diff --git a/harness/bin/Linux/interface b/harness/bin/Linux/interface
--- a/harness/bin/Linux/interface
+++ b/harness/bin/Linux/interface
@@ -20,7 +20,7 @@ fi
 INTERFACE=`ping -R -c1 "${TARGET}" | grep RR | awk '{ print $2 }'`
 
 if [ -z "${INTERFACE}" ] ; then
-    echo "Cannot contace ${TARGET}" >&2
+    echo "Cannot contact ${TARGET}" >&2
     exit 1
 fi
 
